### ISSUE TITLE
Default install instructions are out of date

### ISSUE THREAD

**Issue by txm** [microapps/MoonMail#121]
AFAICT the API to sever less has changed, so the default instructions to MoonMail are out of date.

I've then installed an older version of Serverless, serverless@0.5.2

sls resources deploy displays a lot of warnings, then fails (due to the warnings).

MoonMail$ sls resources deploy
Serverless: WARNING: This variable is not defined: defaultRCU
Serverless: WARNING: This variable is not defined: defaultWCU
Serverless: WARNING: This variable is not defined: sentEmailsRCU
Serverless: WARNING: This variable is not defined: sentEmailsWCU
Serverless: WARNING: This variable is not defined: defaultRCU
Serverless: WARNING: This variable is not defined: defaultWCU
Serverless: WARNING: This variable is not defined: scheduledAtIndexRCU
Serverless: WARNING: This variable is not defined: scheduledAtIndexWCU
Serverless: WARNING: This variable is not defined: defaultRCU
Serverless: WARNING: This variable is not defined: defaultWCU
Serverless: WARNING: This variable is not defined: defaultRCU
Serverless: WARNING: This variable is not defined: defaultWCU
Serverless: WARNING: This variable is not defined: defaultRCU
Serverless: WARNING: This variable is not defined: defaultWCU
Serverless: WARNING: This variable is not defined: recipientsRCU
Serverless: WARNING: This variable is not defined: recipientsWCU
Serverless: WARNING: This variable is not defined: defaultRCU
Serverless: WARNING: This variable is not defined: defaultWCU
Serverless: Deploying resources to stage "dev" in region "us-east-1" via Cloudformation (~3 minutes)...
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: undefined
    at new ServerlessError (/usr/local/lib/node_modules/serverless/lib/Error.js:17:11)
    at ResourcesDeploy.<anonymous> (/usr/local/lib/node_modules/serverless/lib/actions/ResourcesDeploy.js:244:25)
    at ResourcesDeploy.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate](/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback](timers.js:514:5)

If I hard code the above named variables in s-resources-cf.json then deploy gets further, but then gets what looks like other AWS permission errors.

My IAM user is an Admin.

$ more s-variables-dev-us-east-1.json
{
  defaultRCU: 2, // just in case thus made it through to s-resources-cf.json
  defaultWCU: 2, // but they didn't
  sentEmailsRCU: 2,
  sentEmailsWCU: 2,
  scheduledAtIndexRCU: 2,
  scheduledAtIndexWCU: 2,
  recipientsRCU: 2,
  recipientsWCU: 2,
  apiHost: "txm.net"
}

Not really sure what else I can try :/

**Comment by davidgf** [comment]
@txm Are you specifying region and stage when you run `sls resources deploy`? Also, can you go to your AWS Dashboard and check the CloudFormation section? If you select there MoonMail's stack you'll be able the history of events, which are much more descriptive that the serverless error, and we can find out what's going on there :)

**Comment by txm** [comment]
Hi @davidgf I've now learned a bit more about SLS, parameters and _meta variables :)

The furthest I can get now is:

	16:22:40 UTC+0100	CREATE_FAILED	AWS::S3::Bucket	StaticDataBucket	static.moonmail.dev.us-east-1 already exists

	16:22:40 UTC+0100	CREATE_FAILED	AWS::S3::Bucket	RecipientsImportS3Bucket	recipients.moonmail.dev.us-east-1 already exists

I can't see those buckets listed in the S3 console.

**Comment by davidgf** [comment]
@txm actually bucket names must be globally unique across all AWS accounts. So, your best bet is to change the bucket name you're using by modifying [two values](https://github.com/microapps/MoonMail/blob/master/s-templates.json#L91-L92) in `s-templates.json`. Also, keep in mind that in our CloudFormation template we set `DeletionPolicy` to `Retain`, which means that tables won't be automatically deleted upon CF rollbacks and you will probably have to remove them if they were created.

**Comment by txm** [comment]
> @txm actually bucket names must be globally unique across all AWS accounts.

ah ha, I should have spotted that.

> Also, keep in mind that in our CloudFormation template we set DeletionPolicy to Retain

(y) perfect, that's saved me a lot of time manually deleting tables :)

```
$ sls function deploy -s dev -r us-east-1
Serverless: Deploying functions in "dev" to the following regions: us-east-1
Serverless: / uglify-js failed on _meta/_tmp/createCampaign@1474535486769/node_modules/joi/lib/index.js : SyntaxError: Unexpected token name «i», expected punc «;» (line: 168, col: 17, pos: 3747)

Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/andy/Development/MoonMail/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
```

I feel so close, yet so far.

I can't tell if I have an unfortunate mismatch of npm modules, if this is occurring with a Moomail config or if it's Serverless dependancies .. or something else!

**Comment by davidgf** [comment]
@txm short answer:
```
cd /your/moonmail/path/api
npm i emitter
```

Long answer: a dependency in MoonMail requires [batch](https://github.com/visionmedia/batch), which in fact requires `emitter` for browsers, as you can see in [its package.json](https://github.com/visionmedia/batch/blob/master/package.json#L17). Since we are using [Serverless Babel Runtime](https://github.com/serverless/serverless-runtime-babel), which uses [browserify](https://github.com/substack/node-browserify) for deployments and tries to install browser dependencies as well. That said, Serverless Babel Runtime allows you to pass certain parameters to `browserify`, like `exclude` or `ignore`, so you could try to avoid installing `emitter`.

**Comment by mfrye** [comment]
@davidgf I'm almost there as well but currently stuck here when trying to do initial deploy: 


```
Serverless: WARNING: This variable is not defined: sendCampaignTopicARN  
Serverless: WARNING: This variable is not defined: sendEmailsTopicARN  
Serverless: WARNING: This variable is not defined: sentEmailsTopicARN  
Serverless: WARNING: This variable is not defined: projectBucket  
/Users/michael/.node/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: ServerlessError: An error occurred while provisioning your cloudformation: The following resource(s) failed to create: [AttachSenderTopic, PrecompileCampaignTopic, SentEmailsTable, SendCampaignTopic, PrecompileEmailTopic, AttachRecipientsTopic, ClicksStream, SentEmailsTopic, CampaignsTable, TemplatesTable, FreeUsersSendEmailQueue, UsersTable, IamRoleLambda, AttachListRecipientsTopic, StaticDataBucket, UnsubscribedRecipientTopic, LinksTable, UpdateListImportStatusTopic, EmailAdminsTopic, ListsTable, EmailNotificationsTopic, AttachRecipientsCountTopic, OpensStream, UpdateCampaignTopic, SendEmailsTopic, RecipientsImportS3Bucket, ReportsTable].
```

Do I need to set all these variables?

**Comment by alexandresaiz** [comment]
@mfrye please post this question in StackOverflow make sure to tag it with moonmail: http://stackoverflow.com/questions/tagged/moonmail

**Comment by hoducha** [comment]
I got the same issue as @mfrye

**Comment by alexandresaiz** [comment]
@hoducha can you please post this question in StackOveflow and make sure to tag it with moonmail:
http://stackoverflow.com/questions/tagged/moonmail

Please ping us here so we make sure to answer you there. This way we have the knowledge base built in a more open place where it can help many other people rather than in a one single issue. Thanks!

**Comment by hoducha** [comment]
I've posted the question in StackOverflow. Thanks @alexandresaiz.

**Comment by w3update** [comment]
I am facing the same issue http://stackoverflow.com/questions/41618989/moonmail-deploy-function-uglify-js-errors

is this fixed?

**Comment by alexandresaiz** [comment]
@davidgf ping

**Comment by davidgf** [comment]
@w3update actually we couldn't replicate the issue. Do those errors abort the deployment for you?

**Comment by w3update** [comment]
yes also its seems app is not up to date to match with current version of serverless configuration and commands I had to downgrade the serverless to create cloud template then I stuck in "uglify-js-erros" it killed the uploading of function on AWS Lambda in mid way.

**Comment by davidgf** [comment]
@w3update MoonMail is developed with Serverless v0.5, v1.x introduced major breaking changes, it still lacks some features we heavily rely on and which are present in v0.5. 
In regards of the uglify errors, it doesn't seem to get along `Joi`, although we also get some of those errors and it's neither aborting deployment nor breaking the correct functioning of the app.

**Comment by mfrye** [comment]
I tried getting this working back in October and tried again this weekend. Same stuff. I appreciate the idea of open sourcing all this, but after 4 hours in over the weekend I was seething. 

I used Serverless 0.5.2.

I made it through figuring out the variables by going to Gitter and Stackoverflow - there are no explicit docs on this. Then I got caught up in deployment. The app deploys to Cloud Formation and returns a success, but after further investigation half the instances never completed and the whole process hangs.

**Comment by alexandresaiz** [comment]
@mfrye if you pose concrete question/s of the issues in SO, the community will definitely help you. I can tell you there's some dozens of developers who have successfully deployed MoonMail in their AWS account.

**Comment by mfrye** [comment]
@alexandresaiz yeah, I'll have to do that.

My post was more a comment on the general state of documentation here. This seems like an awesome tool, but figuring out how to set it up is a pain.

**Comment by alexandresaiz** [comment]
@mfrye please post your questions in SO and we'll help to death so you can have this fully working.
