### ISSUE TITLE
need some clarification?

### ISSUE THREAD

**Issue by suriyaJaay** [microapps/MoonMail#141]
could you pls tell me , is that possible to integrate it with MEAN stack app.?

if possible means kindly guide me ?

thank you

**Comment by alexandresaiz** [comment]
@suryia please post this question in StackOverflow

**Comment by suriyaJaay** [comment]
but why ? i thought this is the right place to ask this question on Moonmail .

**Comment by alexandresaiz** [comment]
No. Your question is not an issue. Your question is too broad and if added within StackOverflow it will help many other people in case they have the same question.

**Comment by alexandresaiz** [comment]
Please share the url of your question and we will make sure it gets anawered as soon as posible

**Comment by suriyaJaay** [comment]
well. dude, one thing you need understand. if i asking this question in SO they'll ask me about "do you want us to work for you". if i really have an issue in my app, it make sense for ask qstin in SO. but it seems not to be like that. you're the app owner so you should know about whthr its possible or not.. well its okay 

and thanks alot for your quick response.  am gonna try to make my own.

see ya buddy

**Comment by alexandresaiz** [comment]
Well dude. Good luck in building your own. I've been trying to help you and to help others by telling you to post on SO. As you clearly say: people in SO will say: we're not going to do the work for you.
So it's clear then that you don't have a question but laziness problems. Even with those problems I was willing to help and you then come with such a nasty answer with unrespectful tone. Then yes, good luck in building yours. Do remember to open source it once you have it fully functional 😜😂

**Comment by suriyaJaay** [comment]
hold on bro. this is not unrespectful tone. is just said what i thought. before that am totally new mean stack i don't have idea about. while surfing for the solution for my problem had came across your repo that's it .. 

before that i just put my doubts in SO once but none respond yet. finally i did it for myself.  this is not lazy and hard attitude buddy. 

again am saying if any issues my app i can ask then anyone can help to achieve. but no one ready to explain to integrate two different techies.  am here to also ready help. okay (being beginner, give me nice title "unrespectful  and laziness ") that's very nice
