### ISSUE TITLE
Serverless V1.0

### ISSUE THREAD

**Issue by jethrolam** [microapps/MoonMail#157]
Is it part of your roadmap to switch from serverless v0.5 to v1.0?

**Comment by alexandresaiz** [comment]
@jethrolam we haven't made any decison yet

**Comment by pdutt111** [comment]
v0.5 has been deprecated and its getting hard to get this to work without a tutorial for the newer serverless have you made a decision yet on this?

**Comment by DriesArnolds** [comment]
Serverless 1.0 is out for 15 months now (currently at 1.25). It would be good for confidence and developer acceptance to at least have a plan of how and when to switch.

It also makes spinning up a test install harder than it needs to be.
