### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by poisa** [microapps/MoonMail#160]
I've been looking into this project because the idea of having the whole system be a collection of Lambda functions seems very appealing. As a matter of fact, a few years ago I wrote some software that does pretty much the same as MoonMail does and it is due for an update as some specs have changed. I'm evaluating porting my software to Lambda or just adapting the thing to use MoonMail.

I have the following questions:

1. In my tests using Serverless, I noticed that when I changed a resource name (like the name of a DynamoDb table) and redeployed, there was no warning and the old table and its contents were destroyed. I think that a simple mistake like an extra character in the config file resulting in the deletion of all data on a database is pretty risky. How do you handle this kind of issue?

2. Regarding sending email through SES. How do you handle throttling when you reach the sending limit for a particular account? Do you do exponential backoffs? I can't seem to find this in the code base. I'll be very grateful if you could point me in the general area in the repo where this happens.

I do have other questions but I'll wait till I'm more familiar with the repo to ask them. 

Thanks!

**Comment by alexandresaiz** [comment]
@poisa seria posible de tu parte postear estas preguntas por separado en stackoverflow? Sob interesantes y genericas lo suficiente como para 'vivir' allí. Pásanos el enlace y nos encargaremos de responderte allí.

**Comment by poisa** [comment]
Ahí va!
http://stackoverflow.com/questions/41860851/moonmail-lambda-architecture-with-serverless

**Comment by alexandresaiz** [comment]
Gonna answer in s/o

**Comment by poisa** [comment]
Hey @alexandresaiz someone at StackOverflow attempted to answer this but the weren't exactly sure about the second question. Please do jump in if/when you have the time.
