### ISSUE TITLE
Re triggering a Lambda send function

### ISSUE THREAD

**Issue by poisa** [microapps/MoonMail#166]
When there is a message in a user SQS queue, an alarm is triggered and an SNS notification starts the Lambda send email process. If the Lambda function throws an exception and does not re-invoke itself again to send the rest of the batch, **how do you start the process again?** SNS will only send notifications as the alarm state changes but in this case the state will remain the same.

**Comment by alexandresaiz** [comment]
Hi @poisa can you please post the question on SO so the community can profit from your question in the future?

**Comment by poisa** [comment]
http://stackoverflow.com/q/42331975/255260
