### ISSUE TITLE
MoonMail cannot be deploy on first try due to DynamoDB and CloudFormation limitations

### ISSUE THREAD

**Issue by gabrielrobert** [microapps/MoonMail#167]
As seen on SO:

http://stackoverflow.com/questions/42492510/dynamodb-limitations-when-deploying-moonmail

**Comment by davidgf** [comment]
Hi @gabrielrobert, thanks for your interest in the project.
So, as far as I understood in your SO question, you couldn't deploy MoonMail because of your account limits, right? In that case, I guess that not being able to provide the needed resources is not a MM issue

**Comment by ilearnbydoing** [comment]
Hi,
I am not able to update s-resources-cf-dev-useast1.json 
when I update the file by reducing number of table instances
and then after issuing the command 
sls resources deploy
it gets overwritten with default one 

i am using serverless v0.5.4 with Node v6.11.4
Note: I am not very much familiar with stackoverflow and have less reputation to do anything with new account, any help here appreciated.
thanks
