### ISSUE TITLE
default installation process not working

### ISSUE THREAD

**Issue by w3update** [microapps/MoonMail#168]
Hi,

when I execute this command 
sls project init -c -n your-lower-case-project-name

I get this message (in screenshot).

![image](https://cloud.githubusercontent.com/assets/4979654/23548146/24e99fec-002c-11e7-89ac-8b77629695d9.png)

Please guide.

**Comment by alexandresaiz** [comment]
Can you please post this question in SO with tag: stackoverflow.com/tags/moonmail

so we can make sure the answer helps the rest?

**Comment by kidsil** [comment]
Couldn't find an SO post for this, I'm having the same issue, what is the solution?
