### ISSUE TITLE
cheerio, cuid, and liquid-nodes deps

### ISSUE THREAD

**Issue by ldenman** [microapps/MoonMail#20]
```
 cd MoonMail
 npm install
 sls project init -c -n moonmail
 sls resources deploy
 sls function deploy
 npm install liquid-node --save
 sls function deploy
 npm install cheerio --save
 sls function deploy
 npm install --save cuid
 sls function deploy
```
The above are commands from a fresh checkout;. I had to jump through a couple hoops to deploy functions. Is this intended behavior? Thanks

**Comment by davidgf** [comment]
@ldenman we've just updated the README to throw some light on this 😄 . We also have `package.json` files inside subfolders, that will contain dependencies applied to them. If you want to talk about this or just say hi, we have a [Gitter chat room](https://gitter.im/microapps/MoonMail)
