### ISSUE TITLE
Embed json feeds into template feature request

### ISSUE THREAD

**Issue by Sach97** [microapps/MoonMail#315]
Hi guys, cool project ! 

It would be a great idea to add a json feed processing feature for email template to transform the actual content of a json feed into a rendered email.

 **Use case** : personnalized newsletter like Medium

Let's say I have an API that map the id of a suscriber with its interests and return a feed with all the news articles he is interested in and in the MoonMail side I have a recipient field userID.

For example the following url https://myfakenewsapi.com?userId={{userID}}
would return something like this 
```
{
  "categories": [
    {
      "name": "Artificial intelligence",
      "articles": [
        {
          "title": "This is a title",
          "summary": "This an article about artificial intelligence",
          "imageUrl": "https://myurl.com/myimage.jpg"
        }
      ]
    }
  ]
}
```

For the liquid side it would be something like this (I suppose) 

```
{% for category in news.categories %}
    <p>New in {{ category.name}}</p>
    {% for article in category.articles %}
          <p>{{ article.title }}</p>
          <img src="{{ article.imageUrl}}"</img>
          <p>{{ article.summary}}</p>
    {% endfor %}
{% endfor %}
```

**Comment by alexandresaiz** [comment]
@Sach97 thanks for your suggestion! we're indeed working in an RSS feed email parser. Not sure yet whether it will parse xml of json feeds, but in any case it's probable that both would work.
